# Default values for dates.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

aggregator:
  externalport: 80
  port: 3000
  image:
    repository: dagonzadub/aggregator
    tag: latest

iso:
  port: 80
  externalport: 3000
  image:
    repository: dagonzadub/iso-date-service
    tag: stable

utc:
  port: 80
  externalport: 3000
  image:
    repository: dagonzadub/utc-date-service
    tag: stable
