# Default values for dates.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  pullPolicy: IfNotPresent

aggregator:
  externalport: 80
  port: 8000
  image:
    repository: dagonzadub/aggregator
    tag: 1.1

iso:
  port: 80
  externalport: 3000
  image:
    repository: dagonzadub/iso-date-service
    tag: latest

utc:
  port: 80
  externalport: 3001
  image:
    repository: dagonzadub/utc-date-service
    tag: latest
