apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso-date-deployment
  labels:
    app: iso-date-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: iso-date-service
  template:
    metadata:
      labels:
        app: iso-date-service
    spec:
      containers:
      - name: iso-date-service
        image: "{{ .Values.iso.image.repository }}:{{ .Values.iso.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.iso.port }}
