apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator
  ports:
  - protocol: TCP
    port: {{ .Values.iso.externalport }}
    targetPort: {{ .Values.iso.port }}
