apiVersion: v1
kind: Service
metadata:
  name: utc-date-service
spec:
  selector:
    app: utc-date-service
  ports:
  - protocol: TCP
    port: {{ .Values.iso.externalport }}
    targetPort: {{ .Values.iso.port }}
