apiVersion: apps/v1
kind: Deployment
metadata:
  name: utc-date-deployment
  labels:
    app: utc-date-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: utc-date-service
  template:
    metadata:
      labels:
        app: utc-date-service
    spec:
      containers:
      - name: utc-date-service
        image: "{{ .Values.utc.image.repository }}:{{ .Values.utc.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.utc.port }}
