kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-alertmanager
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
